const defaultTransactions = [
  {
    id: 1,
    description: "Fizetés",
    amount: 200000,
    type: "income",
    date: "2025-04-01",
    note: "Havi fizetés a munkahelyről.",
  },
  {
    id: 2,
    description: "Kávé",
    amount: -1500,
    type: "expense",
    date: "2025-04-02",
    note: "Reggeli kávé a kedvenc kávézóban.",
  },
  {
    id: 3,
    description: "Bevásárlás",
    amount: -30000,
    type: "expense",
    date: "2025-03-15",
    note: "Heti bevásárlás az élelmiszerboltban.",
  },
  {
    id: 4,
    description: "Ajándék",
    amount: 50000,
    type: "income",
    date: "2025-04-10",
    note: "Ajándék a születésnapomra.",
  },
  {
    id: 5,
    description: "Villanyszámla",
    amount: -20000,
    type: "expense",
    date: "2025-04-05",
  },
  {
    id: 6,
    description: "Vízszámla",
    amount: -10000,
    type: "expense",
    date: "2025-04-07",
  },
  {
    id: 7,
    description: "Bónusz",
    amount: 100000,
    type: "income",
    date: "2025-04-15",
    note: "Éves bónusz a cégtől.",
  },
  {
    id: 8,
    description: "Mozijegy",
    amount: -5000,
    type: "expense",
    date: "2025-04-20",
    note: "Filmnézés a barátokkal.",
  },
  {
    id: 9,
    description: "Új telefon",
    amount: -150000,
    type: "expense",
    date: "2025-04-25",
    note: "Új telefon vásárlása akciósan.",
  },
  {
    id: 10,
    description: "Eladott XBOX",
    amount: 80000,
    type: "income",
    date: "2025-04-28",
    note: "Régi XBOX eladása online.",
  },
];

export default defaultTransactions;
